name: cooking_app
description: A new Flutter application for cooking.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0 #^0.16.1
  rxdart: ^0.24.0
  provider: ^4.3.2
  webview_flutter: ^1.0.3
  flutter_pdfview: ^1.0.3
  path_provider: ^2.0.1
  http: ^0.13.3
  cached_network_image: ^2.3.2
  device_info: ^2.0.1 #^0.4.2
  package_info: ^2.0.0 #^0.4.3
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.3
  crypto: ^3.0.1 #^2.1.5
  video_thumbnail: ^0.2.5+1
  pull_to_refresh: ^1.6.4
  file_picker: ^3.0.1
  image_picker: ^0.7.4
  video_compress: ^2.0.0
  flutter_image_compress: ^0.6.6 #^0.6.5 #^1.0.0 #
  share: ^2.0.1 #^0.6.5+4
  curved_navigation_bar: ^0.3.4
  flutter_countdown_timer: ^3.0.0
  overlay_support: ^1.0.5
  flutter_native_timezone: ^1.0.10
  dio: ^4.0.0
  flutter_rating_bar: ^4.0.0
  connectycube_sdk: ^2.0.0
  flutter_call_kit: 0.0.2
  flutter_local_notifications: ^5.0.0+4
  flutter_voip_push_notification: ^0.0.3
  audioplayers: ^0.19.0
  firebase_messaging: ^10.0.0 #^8.0.0-dev.14
  firebase_core: ^1.2.0 #^0.7.0
  video_player: ^2.1.6
  table_calendar: ^2.2.3
  js: ^0.6.3
  wakelock: ^0.5.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/app_logo.png
    - assets/login_background.jpg
    - assets/dashboard_home.png
    - assets/dashboard_lesson.png
    - assets/dashboard_booking.png
    - assets/loading_image.png
    - assets/profile_user_default_icon.png
    - assets/add_photo_outline.png
    - assets/dashboard_home.png
    - assets/dashboard_booking.png
    - assets/dashboard_cook_profile.png
    - assets/dashboard_diet.png
    - assets/dashboard_cuisine.png
    - assets/error_image.png
    - assets/dashboard_cook_profile_notification.png
    - assets/dashboard_analytics.png
    - assets/dashboard_flagged_users.png
    - assets/dashboard_all_users.png
    - assets/dashboard_payments.png
    - assets/audio/sample_ringtone.mp3

  fonts:
    - family: Custom
      fonts:
        - asset: assets/fonts/Ultralight.otf
          weight: 200
        - asset: assets/fonts/Thin.otf
          weight: 200
        - asset: assets/fonts/Light.otf
          weight: 300
        - asset: assets/fonts/Regular.otf
          weight: 400
        - asset: assets/fonts/Medium.otf
          weight: 500
        - asset: assets/fonts/Semibold.otf
          weight: 600
        - asset: assets/fonts/Bold.otf
          weight: 700
        - asset: assets/fonts/Heavy.otf
          weight: 800
        - asset: assets/fonts/Black.otf
          weight: 900
